name: Release on Tag
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run build
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*"